config/routes.rb
Rails.application.routes.draw do
  resources :planets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planet.rb
class Planet < ApplicationRecord
    validates_presence_of :name, :diameter, :mass
    validates_uniqueness_of :name
   # above is equal to this one -> validates :name, :diameter, :mass, presence: true
     #validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: %i[ show edit update destroy ]

  # GET /planets or /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1 or /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets or /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to planet_url(@planet), notice: "Planet was successfully created." }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1 or /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to planet_url(@planet), notice: "Planet was successfully updated." }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1 or /planets/1.json
  def destroy
    @planet.destroy

    respond_to do |format|
      format.html { redirect_to planets_url, notice: "Planet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def planet_params
      params.require(:planet).permit(:name, :image_url, :diameter, :mass, :details, :facts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/_form.html.erb
<%= form_with(model: planet) do |form| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
        <% planet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :diameter %>
    <%= form.text_field :diameter %>
  </div>

  <div class="field">
    <%= form.label :mass %>
    <%= form.text_field :mass %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
    <%= form.label :facts %>
    <%= form.text_area :facts %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Diameter</th>
      <th>Mass</th>
      <th>Details</th>
      <th>Facts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.name %></td>
        <td><%= planet.image_url %></td>
        <td><%= planet.diameter %></td>
        <td><%= planet.mass %></td>
        <td><%= planet.details %></td>
        <td><%= planet.facts %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
        <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planet', new_planet_path %>

app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @planet.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @planet.image_url %>
</p>

<p>
  <strong>Diameter:</strong>
  <%= @planet.diameter %>
</p>

<p>
  <strong>Mass:</strong>
  <%= @planet.mass %>
</p>

<p>
  <strong>Details:</strong>
  <%= @planet.details %>
</p>

<p>
  <strong>Facts:</strong>
  <%= @planet.facts %>
</p>

<%= link_to 'Edit', edit_planet_path(@planet) %> |
<%= link_to 'Back', planets_path %>